---
services:
  pingpulse:
    container_name: pingpulse
    command: /app/pingpulse /config.yaml
    image: registry-ui.local.timmybtech.com/pingpulse:latest # Update to your registry of choice
    volumes:
      - "./config.yaml:/config.yaml:ro,Z"
    ports:
      - "8080:8080"
    ## OPTIONAL values that may be needed for some setups
    # network_mode: host # comment out `ports` if using this
    # environment:
    #   - GODEBUG=netdns=cgo
    #   - DEBUG_PING_OUTPUT=1
    # user: root
    # privileged: true
    # security_opt:
    #   - label=disable
    # cap_add:
    #   - NET_RAW
